/* Generated By:JavaCC: Do not edit this line. CMMConstants.java */
package Core;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int ELSE = 2;
  /** RegularExpression Id. */
  int FOR = 3;
  /** RegularExpression Id. */
  int WHILE = 4;
  /** RegularExpression Id. */
  int DO = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int PAUSE = 10;
  /** RegularExpression Id. */
  int CLS = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int REAL = 15;
  /** RegularExpression Id. */
  int STRING = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"int\"",
    "\"void\"",
    "\"main\"",
    "\"print\"",
    "\"pause\"",
    "\"cls\"",
    "<DIGIT>",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "<STRING>",
    "<token of kind 17>",
    "<token of kind 18>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\" >=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
